- src/renderer/components/AnalysisHead.vue
- src/renderer/components/ChessGround.vue
- src/renderer/components/GameBoards.vue
- src/renderer/components/JumpButtons.vue
This fixes some Vue warnings regarding undefined properties and incorrect use of properties.
> Fixed some vue warnings

- src/renderer/components/AnalysisHead.vue
- src/renderer/components/ChessGround.vue
- src/renderer/components/MenuBar.vue
- src/renderer/store.js
> Fixcrazyhouse

- src/renderer/components/AnalysisView.vue
- src/renderer/components/GameBoards.vue
- src/renderer/components/GameInfo.vue
- src/renderer/components/MenuBar.vue
- src/renderer/components/PlayerInfo.vue
- src/renderer/store.js
This adds an element to the UI where some of the header information of the loaded PGN file is displayed. It should complete US1.
> [US1] display PGN header info

- src/renderer/components/AnalysisView.vue
- src/renderer/components/ChessGround.vue
- src/renderer/components/PVLines.vue
- src/renderer/store.js
Hovering PV Lines now highlights the corresponding arrow on the board. And clicking them triggers the corresponding move.
This closes #26.
> Principal Variation Line Navigation - US_9

- src/renderer/components/GameBoards.vue
- src/renderer/components/MenuBar.vue
- src/renderer/components/PgnBrowser.vue
- src/renderer/store.js
This adds a very simple PGN browser to select a game from a file containing multiple games.
> US4 PGN browser

- src/renderer/components/ChessGround.vue
- src/renderer/components/ChessPocket.vue
- src/renderer/components/EvalBar.vue
> Fix issue34

- src/renderer/components/EvalPlot.vue
- src/renderer/components/GameBoards.vue
- src/renderer/components/Mode960.vue
- src/renderer/store.js
> removed ffish-es6, added startFen to store

- src/renderer/components/GameBoards.vue
- [x ] PGN file loads correctly
- [ x] Navigating through the move history works
- [ x] Starting the engine shows moves (test for both sides)
- [ x] Selecting a different variant loads a new board with the variant and you can make moves on the board
- [ x] In Crazyhouse the pocket pieces are shown and you can drop pieces
> now when the engine isrunning the elements now longer move around

- src/renderer/components/AnalysisView.vue
- src/renderer/components/ChessGround.vue
> now the engine arrows are on the correct line

- src/renderer/store.js
Fixes #80. We now wait with pushing the game moves until the variant change has fully completed.
> Fix loading PGN with different variant

- src/renderer/components/SettingsTab.vue
This implements a settings tab to change uci options of the engine. (#22)
> US5 engine settings

- static/piece-css/xiangqi/hanjablue.css
- static/piece-css/xiangqi/hanjagreen.css
Makes sure that green and blue piece sets match their label.
> Fix interchanged color sets for hanja pieces

- src/renderer/components/EvalBar.vue
- src/renderer/components/GameBoards.vue
This fixes the eval bar border & makes the progress dimensions relative to the outer height. It also adds a transition to the progress value.
> Refactor Eval Bar

- src/renderer/components/EvalBar.vue
now the bar is "going" in the right direction
> now the bar is "going" in the right direction

- scripts/postinstall.js
- src/renderer/store/engines.js
> Update Fairy-Stockfish engine name & fix postinstall on mac

- src/renderer/assets/cssVars.css
- src/renderer/components/AnalysisHead.vue
- src/renderer/components/BoardStyleSelector.vue
- src/renderer/components/DarkModeSwitch.vue
- src/renderer/components/EvalPlot.vue
- src/renderer/components/EvalPlotButton.vue
- src/renderer/components/GameBoards.vue
- src/renderer/components/MenuBar.vue
- src/renderer/components/Mode960.vue
- src/renderer/components/PgnBrowser.vue
> CSS improvements

- src/renderer/components/EvalPlot.vue
> fix when black starts

- scripts/postinstall.js
- src/renderer/components/ChessGround.vue
- src/renderer/components/EngineStats.vue
- src/renderer/components/GameBoards.vue
- src/renderer/store.js
- src/renderer/store/engines.js
This...
- Readds the accidentally deleted `isJianggi` getter to the store
- Fixes an unlink error in the postinstall script
- Fixes the displayed Fairy-Stockfish version
- Fixes the initially misaligned piece positions in ChessgroundX
- Adjusts engine stats display
> Misc fixes

- src/renderer/components/EvalPlot.vue
- src/renderer/components/EvalPlotButton.vue
> resetting plot works

- src/renderer/components/Mode960.vue
- src/renderer/store.js
> support 960 mode for atomic

- src/renderer/store.js
* Show correct endgame result if we are going through a pgn game.
* This does not solve issue #210 completely, but at least for pgns
> Correct PGN Endgame Result

- package-lock.json
- package.json
- src/renderer/components/AboutTabModal.vue
> changed version name to 0.3.0

- src/renderer/components/AnalysisContainer.vue
- src/renderer/components/EngineConsole.vue
- src/renderer/components/GameBoards.vue
- src/renderer/components/MenuBar.vue
- src/renderer/components/PVLines.vue
- src/renderer/components/RoundedSwitch.vue
- src/renderer/components/SettingsTab.vue
- src/renderer/components/TournamentHead.vue
- src/renderer/components/TournamentSwitch.vue
- src/renderer/components/TournamentView.vue
- src/renderer/store.js
> TournamentClientVisuals
